
// This file is automatically generated. Do not modify it manually.
// To regenerate this file, need to be in a project that is connected to a Firebase project.
// If you are not seeing a configuration object, you may need to connect to a Firebase project.
//
// TL;DR: This is a public configuration and it's safe to expose.
// https://firebase.google.com/docs/projects/learn-more#config-files-objects
//
// If you are having trouble connecting to Firebase, check the "Third-party cookies" browser setting.
// If you are using Chrome, you can allow cookies for specific sites.
//
// 1. Open Chrome settings.
// 2. Go to "Privacy and security" > "Third-party cookies".
// 3. Under "Allowed to use third-party cookies", click "Add".
// 4. Add the following sites:
//
//    [*.]firebaseapp.com
//    [*.]web.app
//
// This should resolve the issue.

export const firebaseConfig = {
  projectId: "digiport-ptpp",
  appId: "1:915090878008:web:594a85e463f0fa17ea40cd",
  storageBucket: "digiport-ptpp.firebasestorage.app",
  apiKey: "AIzaSyAYSHs1QSt0Q1SjI3pIrUc0yFnIBxxOxX4",
  authDomain: "digiport-ptpp.firebaseapp.com",
  messagingSenderId: "915090878008",
  projectNumber: "915090878008",
  version: "2"
};
