
// This file is automatically generated. Do not modify it manually.
// To regenerate this file, need to be in a project that is connected to a Firebase project.
// If you are not seeing a configuration object, you may need to connect to a Firebase project.
//
// TL;DR: This is a public configuration and it's safe to expose.
// https://firebase.google.com/docs/projects/learn-more#config-files-objects
//
// If you are having trouble connecting to Firebase, check the "Third-party cookies" browser setting.
// If you are using Chrome, you can allow cookies for specific sites.
//
// 1. Open Chrome settings.
// 2. Go to "Privacy and security" > "Third-party cookies".
// 3. Under "Allowed to use third-party cookies", click "Add".
// 4. Add the following sites:
//
//    [*.]firebaseapp.com
//    [*.]web.app
//
// This should resolve the issue.

export const firebaseConfig = {
  projectId: "digital-monitoring-maintenance",
  appId: "1:60393075530:web:8c88b5040cfdb6544d07b3",
  apiKey: "AIzaSyDXO1f_d3kI8gJm2WrMmelJ489hBlzAj0Y",
  authDomain: "digital-monitoring-maintenance.firebaseapp.com",
  measurementId: "G-3849CN8QFG",
  messagingSenderId: "60393075530",
  storageBucket: "digital-monitoring-maintenance.firebasestorage.app"
};
